add configurable client keep-alive duration
MisterTea/EternalTerminal pull request #479
Opened 2021-12-25 16:23 UTC by cfal

hello! thanks for a great tool. this PR (should) make the client keep-alive duration configurable.

i created this because i noticed that reconnection times seemed to be slow sometimes (especially when compared to mosh) and am suffering frequently from lost keys. i realize that UDP is probably better suited for cases where there is frequent switching but many public wifi networks (at least in my locale) has some sort of filtering in place that makes EternalTerminal much more practical to use.

disclaimer: i don't have any actual data that this would improve the situation for my use case, because i'm still having issues building on MacOS M1. but this seemed like a fast enough change that i thought i'd make it and get some feedback :)

please take a look, thanks!

2022-01-05 15:41 UTC, MisterTea requested changes

2022-01-05 15:41 UTC, MisterTea commented on src/terminal/TerminalClientMain.cpp
> +    if (keepaliveDuration < 1 || keepaliveDuration > MAX_CLIENT_KEEP_ALIVE_DURATION) {
Please change this to be a signed integer

2022-01-05 15:41 UTC, MisterTea commented on src/terminal/TerminalClient.cpp
> +                               uint32_t _keepaliveDuration)
Please change to be a signed integer

2022-01-05 15:42 UTC, MisterTea commented
Thanks for this PR!  Overall, it looks great.  I'd like us to stick with signed integers unless we really need to use unsigned.

2022-01-06 04:28 UTC, cfal commented
> Thanks for this PR! Overall, it looks great. I'd like us to stick with signed integers unless we really need to use unsigned.

updated to use ints, thanks!

2022-01-07 20:47 UTC, MisterTea commented
Thanks!

2022-01-07 20:47 UTC, merged